name: Update Fork

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  update-fork:
    name: Update Fork
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Configure git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      
      - name: Add remote for upstream repository
        run: |
          git remote add upstream https://github.com/HarendraRathnayaka/JourneyHub.git  # Replace with your original repository URL
      
      - name: Fetch upstream changes
        run: |
          git fetch upstream
      
      - name: Merge upstream changes into fork
        run: |
          git merge upstream/main  # Change `main` to your main branch name
      
      - name: Push changes to fork
        run: |
          git push origin main  # Change `main` to your main branch name
